[package]
name = "microtick-ssh"
version = "1.4.1"
edition = "2024"

[dependencies]
ssh2 = { version = "0.9.5", features = ["vendored-openssl"] }
openssl = { version = "0.10.71", features = ["vendored"] }

[build-dependencies]
dotenv-build = "0.1.1"
