name: build

on:
    push:
        branches:
            - main
        paths:
            - version

permissions:
    contents: write

jobs:
    build_windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Build app
              run: cargo build -r

            - name: Upload executable
              uses: actions/upload-artifact@v4
              with:
                  name: microtick-ssh.exe
                  path: target/release/microtick-ssh.exe

    build_ubuntu:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Build app
              run: cargo build -r

            - name: Upload executable
              uses: actions/upload-artifact@v4
              with:
                  name: microtick-ssh
                  path: target/release/microtick-ssh
    build_macos:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Build app
              run: cargo build -r

            - name: Upload executable
              uses: actions/upload-artifact@v4
              with:
                  name: microtick-ssh
                  path: target/release/microtick-ssh

    upload_release:
        runs-on: ubuntu-latest

        needs: [build_windows, build_ubuntu, build_macos]

        steps:
            - uses: actions/checkout@v4

            - name: Get the version
              run: echo "APP_VERSION=$(cat version)" >> $GITHUB_ENV

            - name: Download executable Windows
              uses: actions/download-artifact@v4
              with:
                  name: microtick-ssh.exe

            - name: Rename executable Windows
              run: |
                  mv "microtick-ssh.exe" "microtick-ssh_windows.exe"

            - name: Download executable Ubuntu
              uses: actions/download-artifact@v4
              with:
                  name: microtick-ssh

            - name: Rename executable Ubuntu
              run: |
                  mv "microtick-ssh" "microtick-ssh_ubuntu"

            - name: Download executable MacOS
              uses: actions/download-artifact@v4
              with:
                  name: microtick-ssh

            - name: Rename executable MacOS
              run: |
                  mv "microtick-ssh" "microtick-ssh_macos"

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  name: Release ${{ env.APP_VERSION }}
                  tag_name: ${{ env.APP_VERSION }}
                  draft: true
                  files: |
                      microtick-ssh_windows.exe
                      microtick-ssh_ubuntu
