name: build

on:
    push:
        branches:
            - master
        paths:
            - version

permissions:
    contents: write

jobs:
    build_windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Create .env file
              run: |
                  echo "MT_SSH_HOST=${{ secrets.MT_SSH_HOST }}" >> .env
                  echo "MT_SSH_PORT=${{ secrets.MT_SSH_PORT }}" >> .env
                  echo "MT_SSH_USER=${{ secrets.MT_SSH_USER }}" >> .env
                  echo "MT_SSH_PASS=${{ secrets.MT_SSH_PASS }}" >> .env

            - name: Build app
              run: cargo build -r

            - name: Rename executable
              run: ren target\release\microtick-ssh.exe microtick-ssh_windows.exe

            - name: Upload executable
              uses: actions/upload-artifact@v4
              with:
                  name: microtick-ssh_windows.exe
                  path: target/release/microtick-ssh_windows.exe

    build_ubuntu:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Create .env file
              run: |
                  echo "MT_SSH_HOST=${{ secrets.MT_SSH_HOST }}" >> .env
                  echo "MT_SSH_PORT=${{ secrets.MT_SSH_PORT }}" >> .env
                  echo "MT_SSH_USER=${{ secrets.MT_SSH_USER }}" >> .env
                  echo "MT_SSH_PASS=${{ secrets.MT_SSH_PASS }}" >> .env

            - name: Build app
              run: cargo build -r

            - name: Rename executable
              run: mv target/release/microtick-ssh target/release/microtick-ssh-linux

            - name: Upload executable
              uses: actions/upload-artifact@v4
              with:
                  name: microtick-ssh-linux
                  path: target/release/microtick-ssh-linux
    build_macos:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Create .env file
              run: |
                  echo "MT_SSH_HOST=${{ secrets.MT_SSH_HOST }}" >> .env
                  echo "MT_SSH_PORT=${{ secrets.MT_SSH_PORT }}" >> .env
                  echo "MT_SSH_USER=${{ secrets.MT_SSH_USER }}" >> .env
                  echo "MT_SSH_PASS=${{ secrets.MT_SSH_PASS }}" >> .env

            - name: Build app
              run: cargo build -r

            - name: Rename executable
              run: mv target/release/microtick-ssh target/release/microtick-ssh-macos

            - name: Upload executable
              uses: actions/upload-artifact@v4
              with:
                  name: microtick-ssh-macos
                  path: target/release/microtick-ssh-macos

    upload_release:
        runs-on: ubuntu-latest

        needs: [build_windows, build_ubuntu, build_macos]

        steps:
            - uses: actions/checkout@v4

            - name: Get the version
              run: echo "APP_VERSION=$(cat version)" >> $GITHUB_ENV

            - name: Download executable Windows
              uses: actions/download-artifact@v4
              with:
                  name: microtick-ssh_windows.exe

            - name: Download executable Ubuntu
              uses: actions/download-artifact@v4
              with:
                  name: microtick-ssh-linux

            - name: Download executable MacOS
              uses: actions/download-artifact@v4
              with:
                  name: microtick-ssh-macos

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  name: Release ${{ env.APP_VERSION }}
                  tag_name: ${{ env.APP_VERSION }}
                  draft: true
                  files: |
                      microtick-ssh_windows.exe
                      microtick-ssh-linux
                      microtick-ssh-macos
